////;User:;
admin
////;Password:;
cMPC_pxn

config
set slot/3/lg type XCTPS
co
//wait;5;;
show slot/3/phy sub all
//cmp;ver: SW:;2.0.7;1;
//cmp;CPLD ;3202:04.06;1;
//cmp;FPGA ;3201:02.11,3204:01.05;1;
//cmp;PCB:;2;1;1;4;

////;#;

call / showmanu 3
//cmp;rootfs: ;$_008RootFS1;1;
//cmp;SN: ;$_003SN1$_004PN1;1;
//cmp;uboot: ;$_007UBoot1;1;
//module;112product信息录入;end;

dr
exit
////;#;
//module;113reset按钮检查;begin;
//wait;;检查reset按钮，串口观察重启过程
//module;113reset按钮检查;end;