telnet 127.0.0.1 3000
##;User:;
admin
##;Password:;
cMPC_pxn

#label;noready;
show / all
#save;readycfg:;10;
#goto;noready;10;false;

at

dr

set slot/1/lg type ACPS_C

#label;noready1;
show / all
#save;readycfg:;10;
#goto;noready1;10;false;

at

set interfaces/eth/gee.1.1 admin up
set interfaces/eth/gee.1.2 admin up
set interfaces/eth/gee.1.3 admin up
set interfaces/eth/gee.1.4 admin up
set interfaces/eth/gee.1.5 admin up
set interfaces/eth/gee.1.6 admin up
set interfaces/eth/gee.1.7 admin up
set interfaces/eth/gee.1.8 admin up
set interfaces/eth/gee.1.1 role uni
set interfaces/eth/gee.1.2 role uni
set interfaces/eth/gee.1.3 role uni
set interfaces/eth/gee.1.4 role uni
set interfaces/eth/gee.1.5 role uni
set interfaces/eth/gee.1.6 role uni
set interfaces/eth/gee.1.7 role uni
set interfaces/eth/gee.1.8 role uni
set interfaces/eth/gee.1.1/ef cir 1000000
set interfaces/eth/gee.1.2/ef cir 1000000
set interfaces/eth/gee.1.3/ef cir 1000000
set interfaces/eth/gee.1.4/ef cir 1000000
set interfaces/eth/gee.1.5/ef cir 1000000
set interfaces/eth/gee.1.6/ef cir 1000000
set interfaces/eth/gee.1.7/ef cir 1000000
set interfaces/eth/gee.1.8/ef cir 1000000

set interfaces/eth/ge.1.1 admin up
set interfaces/eth/ge.1.2 admin up
set interfaces/eth/ge.1.3 admin up
set interfaces/eth/ge.1.4 admin up
set interfaces/eth/ge.1.5 admin up
set interfaces/eth/ge.1.6 admin up
set interfaces/eth/ge.1.1 role uni
set interfaces/eth/ge.1.2 role uni
set interfaces/eth/ge.1.3 role uni
set interfaces/eth/ge.1.4 role uni
set interfaces/eth/ge.1.5 role uni
set interfaces/eth/ge.1.6 role uni
set interfaces/eth/ge.1.1/ef cir 1000000
set interfaces/eth/ge.1.2/ef cir 1000000
set interfaces/eth/ge.1.3/ef cir 1000000
set interfaces/eth/ge.1.4/ef cir 1000000
set interfaces/eth/ge.1.5/ef cir 1000000
set interfaces/eth/ge.1.6/ef cir 1000000

cr pmap/ethac l2acge {default={cos='ef',cir=1000000}}
cr interfaces/eth/gee.1.1 1 {admin='up',mode='port', qos='l2acge'}
cr interfaces/eth/gee.1.2 1 {admin='up',mode='port', qos='l2acge'}
cr interfaces/eth/gee.1.3 1 {admin='up',mode='port', qos='l2acge'}
cr interfaces/eth/gee.1.4 1 {admin='up',mode='port', qos='l2acge'}
cr interfaces/eth/gee.1.5 1 {admin='up',mode='port', qos='l2acge'}
cr interfaces/eth/gee.1.6 1 {admin='up',mode='port', qos='l2acge'}
cr interfaces/eth/gee.1.7 1 {admin='up',mode='port', qos='l2acge'}
cr interfaces/eth/gee.1.8 1 {admin='up',mode='port', qos='l2acge'}
cr interfaces/eth/ge.1.1  1 {admin='up',mode='port', qos='l2acge'}
cr interfaces/eth/ge.1.2  1 {admin='up',mode='port', qos='l2acge'}
cr interfaces/eth/ge.1.3  1 {admin='up',mode='port', qos='l2acge'}
cr interfaces/eth/ge.1.4  1 {admin='up',mode='port', qos='l2acge'}
cr interfaces/eth/ge.1.5  1 {admin='up',mode='port', qos='l2acge'}
cr interfaces/eth/ge.1.6  1 {admin='up',mode='port', qos='l2acge'}

cr ccc 100 {admin='up'}
cr ccc 101 {admin='up'}
cr ccc 102 {admin='up'}
cr ccc 103 {admin='up'}
cr ccc 104 {admin='up'}
cr ccc 105 {admin='up'}
cr ccc 106 {admin='up'}

cr interfaces/eth/ge.1.6/1  service {_='ccc',vpn='ccc/100'}
cr interfaces/eth/gee.1.1/1 service {_='ccc',vpn='ccc/100'}
cr interfaces/eth/gee.1.2/1 service {_='ccc',vpn='ccc/101'}
cr interfaces/eth/gee.1.3/1 service {_='ccc',vpn='ccc/101'}
cr interfaces/eth/gee.1.4/1 service {_='ccc',vpn='ccc/102'}
cr interfaces/eth/gee.1.5/1 service {_='ccc',vpn='ccc/102'}
cr interfaces/eth/gee.1.6/1 service {_='ccc',vpn='ccc/103'}
cr interfaces/eth/gee.1.7/1 service {_='ccc',vpn='ccc/103'}
cr interfaces/eth/gee.1.8/1 service {_='ccc',vpn='ccc/104'}
cr interfaces/eth/ge.1.4/1  service {_='ccc',vpn='ccc/104'}
cr interfaces/eth/ge.1.3/1  service {_='ccc',vpn='ccc/105'}
cr interfaces/eth/ge.1.2/1  service {_='ccc',vpn='ccc/105'}
cr interfaces/eth/ge.1.1/1  service {_='ccc',vpn='ccc/106'}
cr interfaces/eth/ge.1.5/1  service {_='ccc',vpn='ccc/106'}

##;#;
#cmpn;;ERROR;

exit
#wait;4;等待治具设备...;