manu clear

manu set mac macformat$_006EthMac1
manu set sn $_003SN1
manu set pn $_004PN1
manu set boot $_015boot
##manu set vendor $_016vendor

manu check
#cmp;manu;all ok;

date

telnet 127.0.0.1 3000
##;User:;
admin
##;Password:;
cMPC_pxn

#label;noready;
show / all
#save;readycfg:;10;
#goto;noready;10;false;

call / showmanu 1
#sleep;4;...;
#;SUCCESS!;
#cmp;mac: ;macformat$_006EthMac1;1;
#cmp;sn: ;$_003SN1;1;
#cmp;pn: ;$_004PN1;1;
#cmp;boot: ;$_015boot;1;
##cmp;vendor: ;CORIANT;1;
#;#;

quit

manu sysclear

date