telnet 127.0.0.1 3000
##;User:;
admin
##;Password:;
cMPC_pxn

call slot/1/2/phy setmanu {sn="$_003SN1",vendor="$_016vendor"}

call slot/1/2/phy getmanu 
#;SUCCESS!;
#cmp;sn=;$_003SN1;1;
#cmp;vendor= ;$_016vendor;1; 
#;#;

call slot/2/2/phy setmanu {sn="$_009SN2",vendor="$_016vendor"}

call slot/2/2/phy getmanu 
#;SUCCESS!;
#cmp;sn=;$_009SN2;1;
#cmp;vendor= ;$_016vendor;1; 
#;#;

quit