//module;111指示灯检查;begin;
////;User:;
admin
////;Password:;
cMPC_pxn

d
hsl c=8,m=hwtest,a=0
hsl c=9,m=hwtest,a=0
hsl c=7,m=hwtest,a=1
//wait;50;slot7灯是否全亮?;
hsl c=7,m=hwtest,a=0
//wait;50;slot7灯是否全灭?;
hsl c=7,m=hwtest,a=1

hsl c=10,m=hwtest,a=1
//wait;50;slot10灯是否全亮?;
hsl c=10,m=hwtest,a=0
//wait;50;slot10灯是否全灭?;
hsl c=10,m=hwtest,a=1
exit
//module;111指示灯检查;end;
//module;112硬件信息查询;begin;
//sleep;5;...;