##;login:;
a
##;Password:;
a
##;$;
su
##;Password:;
root

manu clear
manu set mac macformat$_012EthMac2
manu set sn $_009SN2
manu set pn $_010PN2
manu set vendor CORIANT

cat proc/cmdline
#cmp;uboot=;Oct 28 2013-19:01:47;
#cmp;mem=;0x1e000000 reserve=0x1e000000,0x2000000 errcode=0x0;

cat /etc/buildtime
#cmp;;2013-10-15 11:27:5;

manu set boot $_015boot

manu check
#cmp;manu;all ok;

exit

##;$;