////;User:;
admin
////;Password:;
cMPC_pxn

co

//wait;5;5秒后注意观察业务瞬断后恢复正常;
set cfp/3 apscmd manualswitch::work
co
//wait;;观察业恢复正常;

//wait;5;5秒后注意观察业务瞬断后恢复正常;
set cfp/1 apscmd manualswitch::work
set cfp/2 apscmd manualswitch::work
co

//sleep;10;init;

//sleep;40;xct switch;

exit
//module;108slot9TDM和GE业务测试;begin;
//wait;;使用备xctTDM和GE业务测试5分钟;
//module;108slot9TDM和GE业务测试;end;