////;User:;
admin
////;Password:;
cMPC_pxn
option page off
secu
idletime admin 9999999
exit
co

top
edit /interfaces/$_020EthetnetInstrumentPort1
top
edit /interfaces/$_020EthetnetInstrumentPort1/send
top
edit /interfaces/$_020EthetnetInstrumentPort1/send
set / bw_cnt 1844
top
edit /interfaces/$_020EthetnetInstrumentPort1/send/stream1
top
edit /interfaces/$_020EthetnetInstrumentPort1/send/stream1/cstream
set / bw_cnt 1844
set / bw_percent 90000000
top
edit /interfaces/$_020EthetnetInstrumentPort1/send/stream1/pstream
set / framesize_base 64
top
edit /interfaces/$_020EthetnetInstrumentPort1/send/stream1/pstream/protocol
set / da_value da00.0000.0000
set / sa_value ca00.0000.0000
top
edit /interfaces/$_020EthetnetInstrumentPort1/send/stream1/pstream/protocol/vlan
top
edit /interfaces/$_020EthetnetInstrumentPort1/send/stream1/pstream/udf
co
top
call / config_send $_020EthetnetInstrumentPort1 
top
edit /interfaces/$_020EthetnetInstrumentPort1/send
top
edit /interfaces/$_021EthetnetInstrumentPort2
top
edit /interfaces/$_020EthetnetInstrumentPort1/send
top
edit /interfaces/$_020EthetnetInstrumentPort1/send/stream1
top
edit /interfaces/$_020EthetnetInstrumentPort1/send/stream1/cstream
top
edit /interfaces/$_020EthetnetInstrumentPort1/send/stream1/pstream
top
edit /interfaces/$_020EthetnetInstrumentPort1/send/stream1/pstream/protocol
top
edit /interfaces/$_020EthetnetInstrumentPort1/send/stream1/pstream/protocol/vlan
top
edit /interfaces/$_020EthetnetInstrumentPort1/send/stream1/pstream/udf
co
top
call / config_send $_020EthetnetInstrumentPort1  
top
edit /interfaces/$_021EthetnetInstrumentPort2/send
top
edit /interfaces/$_021EthetnetInstrumentPort2/send
set / bw_cnt 1844
top
edit /interfaces/$_021EthetnetInstrumentPort2/send/stream1
top
edit /interfaces/$_021EthetnetInstrumentPort2/send/stream1/cstream
set / bw_cnt 1844
set / bw_percent 90000000
top
edit /interfaces/$_021EthetnetInstrumentPort2/send/stream1/pstream
set / framesize_base 64
top
edit /interfaces/$_021EthetnetInstrumentPort2/send/stream1/pstream/protocol
set / da_value ca00.0000.0000
set / sa_value da00.0000.0000
top
edit /interfaces/$_021EthetnetInstrumentPort2/send/stream1/pstream/protocol/vlan
top
edit /interfaces/$_021EthetnetInstrumentPort2/send/stream1/pstream/udf
co
top
call / config_send $_021EthetnetInstrumentPort2 

//sleep;1;...;
exit