##;login:;
a
##;Password:;
a
##;$;
su
##;Password:;
root

#module;123product信息录入;begin;
#module;124product信息录入(slot10);begin;
manu clear
manu set mac macformat$_012EthMac2
manu set sn $_009SN2$_010PN2

cat proc/cmdline
#cmp;uboot=;Jun 07 2013-09:07:20;
cat /etc/buildtime
#cmp;2013-05-27; 14:41:38;

manu set boot $_015boot
manu set vendor $_016vendor

manu check
#cmp;manu;all ok;

exit
#module;124product信息录入(slot10);end;
##;$;