#wait;;连上串口线,power on;
##;stop key:< >;
#module;101mac设置及CPLD加载;begin;

print
set ethaddr $_006EthMac1
set bootargs root=/dev/mtdblock3 rw rootfstype=jffs2 console=$consoledev,$baudrate $othbootargs uboot=$ubootver
set bootcmd nand read \$loadaddr 0x200000 0x200000\;nand read \$fdtaddr 0x100000 0x100000\;bootm \$loadaddr - \$fdtaddr
nand erase 0x2600000 0xd800000
save
print
#cmp;ethaddr=;$_006EthMac1;1;17;

reset
#sleep;30;单板启动;