##;login:;
a
##;Password:;
a
##;$;
su
##;Password:;
root
dmesg 
##;/ #;
#buffcut;*********************hwtest******************;; 
#module;118boardtype(slot3-SGSP-A);begin;
#cmp;board type ;SGSP-A;1;8;1;
#module;118boardtype(slot3-SGSP-A);end;
#cmp;pcb version ;1;0;4;1;
#module;119cpld(slot3-4.c);begin;
#cmp;CPLD_ID ;3003;1;4;2;
#cmp;version  ;4.c;1;3;3;
#cmp;CPLD            ;ok;1;2;4;
#module;119cpld(slot3-4.c);end;
#module;120boardonline(slot3-ok);begin;
#cmp;board online;ok;1;5;2;
#module;120boardonline(slot3-ok);end;
#cmp;AD9518_1 ;ok;1;2;5;
#cmp;AD9518_2 ;ok;1;2;6;
#module;121temp(slot3-ok);begin;
#save;temp : ;7;0;5;
#saveconst;29;125;
#saveconst;71;126;
#count;125;<;7;
#count;126;>;7;
#module;121temp(slot3-ok);end;
#cmp;slot 8: com:;ok;1;2;8;
#cmp;hg1:;up;1;2;10;
#cmp;slot 9: com:;ok;1;2;11;
#cmp;hg3:;up;1;2;13;
#cmp;1588;ok;1;3;14;
#module;122port(slot3-ok);begin;
#cmp;ge1 :;up         ge2 :up         ge3 :up         ge4 :up         ge5 :up;         
#cmp;ge6 :;up         ge7 :up         ge8 :up         ge9 :up         ge10:up;         
#cmp;ge11:;up         ge12:up;         
#cmp;inp1:;up         inp2:up         inp3:up;
#cmp;FPGA1_ID  ;3001   version  2.7;
#cmp;FPGA2_ID  ;3002   version  3.2;
#cmp;FPGA1 ;ok        FPGA2 ok;
#cmp;LIU_1 ;ok        LIU_2 ok        LIU_3 ok        LIU_4 ok;    
#cmp;TDM1 ;ok      TDM2 ok      TDM3 ok      TDM4 ok;      
#cmp;TDM5 ;ok      TDM6 ok      TDM7 ok      TDM8 ok; 
#cmp;ge1 :;sfp        ge2 :sfp        ge3 :sfp        ge4 :sfp        ge5 :sfp;  
#cmp;ge6 :;sfp        ge7 :sfp        ge8 :sfp        ge9 :sfp        ge10:sfp;  
#cmp;ge11:;sfp        ge12:sfp  
#cmp;port1 :;sfp      port2 :sfp      port3 :sfp      port4 :sfp      port5 :sfp;  
#cmp;port6 :;sfp      port7 :sfp      port8 :sfp;      
#cmp;FE T0 slot 8; OK;
#cmpn;FE T0 slot 8; FAIL;
#cmp;FE T0 slot 9; OK;
#cmpn;FE T0 slot 9; FAIL;
#module;122port(slot3-ok);end;
rm –r /appdisk/*
exit
##;$;
#module;112硬件信息查询;end;