mkdir /appdisk/nepkg/

#sftp;tx;D:\Éú²ú²âÊÔ°æ±¾\V2.3.0\$_022appname.tar.gz;/appdisk/nepkg/$_022appname.tar.gz;

tar -C /appdisk/nepkg -zxvf /appdisk/nepkg/$_022appname.tar.gz
##;#;
luacmd.lua
##;> ;
pga._progcpld(0,"/appdisk/nepkg/$_022appname/soft_ptn64/cxt20c/fpga/cxt3305v0107.bin")
#sleep;2;delay 2s;
#cmp;cpu test is e0000000;the cpld download is start;
##;now reboot the system;
##;> ;
#ctrld;

echo -n $_022appname > /appdisk/nepkg/active
reboot
#sleep;120;...;