////;User:;
admin
////;Password:;
cMPC_pxn
co
show slot/1/phy sub all 
//cmp;ver: SW:;2.0.7;1;5;
show slot/2/phy sub all 
//cmp;ver: SW:;2.0.7;1;5;
//module;104生产信息录入;end;
call / showmanu 1
//cmp;rootfs: ;$_008RootFS1;1;
//cmp;SN: ;$_003SN1$_004PN1;1;
//cmp;uboot: ;$_007UBoot1;1;
//module;106product信息录入;end;
call / showmanu 2
//cmp;rootfs: ;$_008RootFS1;1;
//cmp;SN: ;$_009SN2$_010PN2;1;
//cmp;uboot: ;$_007UBoot1;1;
//module;106product信息录入;end;
dr
exit
//;#;