##;stop key:< >;
#sleep;0;...;

print
set ethaddr 00:00:00:00:00:00
set bootargs root=/dev/mtdblock3 rw rootfstype=jffs2 console=$consoledev,$baudrate $othbootargs uboot=$ubootver
set bootcmd nand read \$loadaddr 0x200000 0x200000\;nand read \$fdtaddr 0x100000 0x100000\;bootm \$loadaddr - \$fdtaddr
nand erase 0x2600000 0xd800000
save
print
#cmp;ethaddr=;00:00:00:00:00:00;1;17;
reset
#module;101Mac地址设置;end;
#module;102安装升级包并加载cpld;begin;
##;fpga/cxt2003v040f.bin;
#wait;90;等待启动完成;