#wait;;连上串口线,待测单盘上电;
##;stop key:< >;

#module;101mac设置;begin;

print
set ethaddr $_006EthMac1
set bootargs root=/dev/mtdblock3 rw rootfstype=jffs2 console=$consoledev,$baudrate $othbootargs uboot=$ubootver
set bootcmd nand read \$loadaddr 0x200000 0x200000\;nand read \$fdtaddr 0x100000 0x100000\;bootm \$loadaddr - \$fdtaddr
nand erase 0x2600000 0xd800000
save
print
#cmp;ethaddr=;$_006EthMac1;1;17;

reset
#module;101mac设置;end;
#wait;30;等待单盘启动；