luacmd.lua
##;> ;
pga._progsucard(1,4,"/appdisk/nepkg/$_022appname/soft_ptn64/cxt80_62g/fpga/cxt3703v0100.jed")
#sleep;2;delay 2s;
#cmp;cpu test is e0000000;the cpld download is start;
##;now reboot the system;
##;> ;
pga._progsucard(1,5,"/appdisk/nepkg/$_022appname/soft_ptn64/cxt80_62g/fpga/cxt3703v0100.jed")
#sleep;2;delay 2s;
#cmp;cpu test is e0000000;the cpld download is start;
##;now reboot the system;
##;> ;
#ctrld;


#wait;;请点击确定后，按reset按钮;